#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
killall -9 sxhkd ksuperkey
killall -q picom

bspc monitor -d I II III IV V VI VII VIII IX X

#bspc config border_width         0
bspc config window_gap          15

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a firefox desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Thunar state=tiled
#bspc rule -a Viewnior state=floating follow=on focus=on


# Border
bspc config focused_border_color        "#22292B"
bspc config normal_border_color         "#22292B"
bspc config active_border_color         "#22292B"


ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

#bash $HOME/.fehbg
#feh --bg-scale ~/.config/bspwm/wallpapers/wall2.png
#
# Autostart
#

# Set display from arandr saved script
#sh ~/.screenlayout/monitor.sh &

# Bar
~/.config/bspwm/bar/launch.sh &

# Notifications
/usr/bin/dunst &

# Polkit
#/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Dex
#dex -a -s /etc/xdg/autostart/:~/.config/autostart/ 

# Picom
picom --experimental-backends &

# Network Applet
#nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
#~/.config/bspwm/scripts/low_bat_notifier.sh

~/.config/bspwm/bin/bspborder &
feh --bg-scale --zoom fill ~/Pictures/wallpapers/wallhaven-kx9ql7.jpg
#xdo lower -N "Polybar"
sleep 5s
xdo lower -N "Polybar"
xdo above -N "Polybar" -t $(xdo id -N Bspwm -n root)
sxhkd &
